name: Tag Workflow
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: 'v1.0.0'
      tag_message:
        description: 'Tag message'
        required: true
        default: 'Release v1.0.0'

jobs:
  tag_commit:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
      
    steps:

      - name: Checkout code
        uses: actions/checkout@v4    
        
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
      - name: Fetch all tags and branches
        run: git fetch --all

      - name: Get latest commit on main branch
        id: get_latest_commit
        run: echo "::set-output name=LATEST_COMMIT::$(git rev-parse origin/develop)"

      - name: Tag latest commit
        run: |
          git tag -a ${{ github.event.inputs.tag_name }} ${{ steps.get_latest_commit.outputs.LATEST_COMMIT }} -m "${{ github.event.inputs.tag_message }}"
          git push origin ${{ github.event.inputs.tag_name }}
