name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: develop

    - name: Set up Git
      run: |
        echo "Setting up Git"
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Authenticate with GitHub
      run: |
        echo "Authenticating"
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}

    - name: Create new branch
      run: |
        echo "Creating new branch release/${{ github.event.inputs.release_version }}"
        git checkout -b release/${{ github.event.inputs.release_version }}
        git push origin release/${{ github.event.inputs.release_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
