name: Weekly Build and Notify

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - '.github/workflows/weekly_checkup.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml    
        
      - name: Run Unit Tests
        run: mvn test --file pom.xml

      - name: Snyk Security Scan
        run: snyk test --all-projects > snyk_report.txt || true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build the project
        run: ./mvnw clean package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk_report.txt

      - name: Notify via Telegram on Failure
        if: always() #for test
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          REPORT_URL="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="The weekly build of the Spring app has failed. Snyk Report and CodeQL Report are available [here]($REPORT_URL)."
